source 'https://rubygems.org'

gem 'puma', '~> 4.3.3'
gem 'rack', '~> 2.2.4'
gem 'sinatra', '~> 3.0.4'
gem 'sinatra-contrib', '~> 3.0.4'
gem 'redis', '~> 4.1.2'
gem 'bunny', '~> 2.14.2'
gem 'connection_pool', '~> 2.2.2'


# These are only used when running as worker. todo: maybe put into separate :worker bundle group
gem 'sneakers', '~> 2.11.0'
gem 'statsd-ruby', '~> 1.4.0'



# todo: put into separate :test bundle group
group :test do
  gem 'rack-test', '~> 2.0.2'
  gem 'minitest'
end
